### ISSUE TITLE
Question about the network training.

### ISSUE THREAD

**Issue by OValery16** [facebookresearch/TimeSformer#15]
Thanks to the authors for this brilliant work.

I have an question open question regarding the training process. 

In the timesformer architecture, you are using different type [attention mechanisms](https://github.com/facebookresearch/TimeSformer/blob/64790c29842ac0de2e1250c9b449ee31484655f0/timesformer/models/vit.py#L123), which can be seen as custom layer. However PyTorch has no knowledge of the algorithm you are implementing. It knows only of the individual operations you use to compose your algorithm. As such, PyTorch must execute your operations individually, one after the other. Since each individual call to the implementation (or kernel) of an operation, which may involve the launch of a CUDA kernel, has a certain amount of overhead, this overhead may become significant across many function calls. Furthermore, the Python interpreter that is running our code can itself slow down our program.

As a result, a method of speeding up these attention operations would be to rewrite parts in C++ (or CUDA) and fuse particular groups of operations. This technique is exposed in [pytorch advance tutorial](https://pytorch.org/tutorials/advanced/cpp_extension.html).

With your experience, do you think this is the way to go? If so, from your perspective, how much processing time and GPU memory can we save?

Thank you in advance for your answer

**Comment by gberta** [comment]
I think you are right that it's possible to optimize the efficiency of our model. However, I'm not sure how significant the boost would be if parts of the code were rewritten in C++. Our main goal in this work was to show that it is possible to apply transformer based models on video understanding, rather than maximizing the efficiency of our model. If you experiment with any of these more advanced implementations, do let us know. I would be very curious to know what the speedup gains are.
