### ISSUE TITLE
Missing DATASET.md

### ISSUE THREAD

**Issue by balaganeshmohan** [facebookresearch/TimeSformer#20]
Hello, I am trying to train a custom dataset with 6 classes and n frames per video sample. I'd like to know how to prepare the train and test list for training. Would appreciate if the missing file is restored or a short description is provided in this thread. Thank you.

**Comment by gberta** [comment]
The missing file should be restored now. For some basic instructions on how to train TimesFormer on a custom dataset, please check out my earlier post: https://github.com/facebookresearch/TimeSformer/issues/18#issuecomment-836730798

**Comment by gberta** [comment]
You will probably have to write your own data loader.  You can either incorporate the function that reads frames (from SSv2 data file) into your custom dataset file (based on the kinetics data file), and simply replace the video data decoding step with that frame loading function. Furthermore, instead of reading a single label, you should read in as many labels as you have peer video. Lastly, you will need to change your loss function to "bce_logit" to account for the fact that multiple labels per video are possible.
