### ISSUE TITLE
Failed to meta load video idx 46523 from fmSfLXRLHug; trial 0

### ISSUE THREAD

**Issue by wenyuqing** [facebookresearch/TimeSformer#28]
![image](https://user-images.githubusercontent.com/48059861/118608675-8a933480-b7ec-11eb-9051-c4d3704dd021.png)
I meet this error running the code,could you help me check it?

**Comment by wenyuqing** [comment]
![image](https://user-images.githubusercontent.com/48059861/118762138-406f8900-b8a8-11eb-8003-8598001d4b24.png)
I checked the paths are correct,but for some data the problem still exists, could you please tell me how to solve it?

**Comment by gberta** [comment]
Some of your videos might be non-existent or corrupted. This typically doesn't interfere with the model training, unless there's a very large of corrupted/missing videos.

However, when running the inference process you should make sure that all the videos are valid. Otherwise, the inference code will crash.

**Comment by wenyuqing** [comment]
Thanks a lot for your help!

**Comment by wssxjtu** [comment]
> ![image](https://user-images.githubusercontent.com/48059861/118762138-406f8900-b8a8-11eb-8003-8598001d4b24.png) I checked the paths are correct,but for some data the problem still exists, could you please tell me how to solve it?

Hello，How do you generate the label file that includes the path?
