### ISSUE TITLE
Writing probabilites rather than labels with TEST.SAVE_RESULTS_PATH?

### ISSUE THREAD

**Issue by balaganeshmohan** [facebookresearch/TimeSformer#43]
Hi, I have been trying to do this with no avail. How can I output the softmax of the outputs rather than labels itself? Thank you.

**Comment by gberta** [comment]
I think there's a bug in the original pySlowFast implementation at: https://github.com/facebookresearch/TimeSformer/blob/a5ef29a7b7264baff199a30b3306ac27de901133/tools/test_net.py#L131  

It should be concatenating all_preds, and all_labels instead of all_labels, all_labels. I haven't used this part of the code, but that's my impression after taking a look at it.

**Comment by balaganeshmohan** [comment]
That fixed the issue. Thanks!
